### ISSUE TITLE
Cut dependency on Ring

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialColors#10]
Currently, MaterialColors depends on Ring by using the method #methodsInProtocol:.

We should remove this dependence.

**Comment by pdebruic** [comment]
Thats just the test though right?  Is there a way to mark it as expected failure on GS?

**Comment by pdebruic** [comment]
And really there is no rush on making a release from my point of view.  Take your time.

**Comment by jecisc** [comment]
No, the dependency is directly in the MDLColor class.

I propose to rewrite it like this:

```Smalltalk
allDefaultsColors
	^ self class allMethods select: [ :each | each protocol = #'defaults - colors' ] thenCollect: [ :m | MDLColor perform: m selector ]
```

I hope Gemstone implements #allMethods and #protocol.

**Comment by pdebruic** [comment]
dnu #allMethods and also dnu #protocol


what about #allSelectors and #categoryOfSelector: ?

**Comment by jecisc** [comment]
#allSelectors exists in Pharo but not #categoryOfSelector:

I'll maybe have to create a Platform compatibility package.
